# Generated by Django 6.0.4 on 2026-04-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('college', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('caste_category', models.CharField(max_length=50)),
                ('annual_income', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('skills', models.TextField(help_text='Comma separated skills')),
                ('preferred_domain', models.CharField(max_length=100)),
            ],
        ),
    ]
