# Generated by Django 6.0.4 on 2026-04-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='annual_income',
            new_name='family_annual_income',
        ),
    ]
