# Generated by Django 5.2.5 on 2026-04-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_rename_annual_income_studentprofile_family_annual_income"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
