# Generated by Django 6.0.4 on 2026-04-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentscheme',
            name='required_documents',
            field=models.TextField(default='Income Certificate, Caste Certificate, Aadhaar, Marksheets', help_text='Comma separated documents'),
            preserve_default=False,
        ),
    ]
