# Generated by Django 6.0.4 on 2026-04-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('min_cgpa', models.FloatField(default=0)),
                ('max_income', models.IntegerField()),
                ('eligible_state', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
