# Generated by Django 6.0.4 on 2026-04-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppurtunities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('required_skills', models.TextField(help_text='Comma separated skills')),
                ('domain', models.CharField(max_length=100)),
                ('eligible_year', models.IntegerField()),
            ],
        ),
    ]
