# Generated by Django 6.0.4 on 2026-04-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oppurtunities', '0002_internship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='eligible_year',
            new_name='eligible_academic_year',
        ),
    ]
