# Generated by Django 5.2.5 on 2026-04-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "oppurtunities",
            "0003_rename_eligible_year_internship_eligible_academic_year",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
