# Generated by Django 6.0.4 on 2026-04-08 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('profiles', '0002_rename_annual_income_studentprofile_family_annual_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(max_length=100)),
                ('completed_steps', models.TextField(default='')),
                ('status', models.CharField(default='active', max_length=50)),
                ('last_response', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentbundle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile')),
            ],
        ),
    ]
