# Generated by Django 6.0.4 on 2026-04-08 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_rename_annual_income_studentprofile_family_annual_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_text', models.TextField()),
                ('cover_letter_text', models.TextField()),
                ('checklist', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile')),
            ],
        ),
    ]
